### ISSUE TITLE
Singularity run of docker image crash

### ISSUE THREAD

**Issue by claumer** [koszullab/instaGRAAL#20]
Hi there,

I'm trying to run instaGRAAL, but the only NVIDIA-GPU powered compute I have access to is within an HPC cluster environment. It's difficult therefore to install following the recommendations (no root access to a package manager), and without root, I can't use docker either. 

However, I can build a singularity image from the docker file like so (using Singularity 3.6.4):

singularity build instagraal.sif docker://koszullab/instagraal

When running, I start a new ssh session (with -Y), start an interactive session on the gpu node I wish to use (w/ Tesla V100), using LSF options to enable X forwarding, and run instagraal like:

singularity run --nv instagraal.gif SsphL_hicstuff/ SsphL.genome.fasta instagraal_out/

But all that happens is a brief flutter of an X11 window opening and immediately closing again, a segmentation fault error, and my cursor being returned to me. I have seen similar behavior in non-interactive run modes and on a windows box through putty (with X11 forwarding enabled and using Xming for display). 

I've also tried running like:

DISPLAY=:0 singularity run --nv instagraal.gif SsphL_hicstuff/ SsphL.genome.fasta instagraal_out/

And this just returns:
freeglut (/usr/local/bin/instagraal): failed to open display ':0'

My problem seems similar to issue #13 . But the docker-related part of that issue never seems to have gotten a resolution.

Can you please advise?

Regards,
Chris L

**Comment by fabiengir** [comment]
Hello, 

We recently released a Dockerfile and a docker image on Docker hub (koszullab/instagraal). 

Our strategy was to drop the Xdisplay and run the no-opengl version of instagraal (available here : https://github.com/koszullab/instagraal.git@no_opengl#egg=instagraal), and using nvidia-docker2 (the installation of nvidia-docker2 is really important). The procedure to run instagraal with the DockerFile has been updated on the git hub page.

The Dockerfile seems to work on our different computers, event with quite old GPU (mine is a NVIDIA quadro K200).

 It's a partial solution, since I assume you don't have root acces on the gpu cluster. 

Regarding singularity, we tried to build singularity images but the --nv option of singularity require cuda 11 or we only managed to run instagraal on cuda 10 ( with cuda 11 there is an error regarding missing binaries).

I hope the Docker solution is good enough for you,

Best , 
Fabien G
