### ISSUE TITLE
question about the hicstuff 

### ISSUE THREAD

**Issue by longzhangnation** [koszullab/instaGRAAL#9]
HI,
  I am planning to use the installGRAAL for my 3C data. I know it is necessary to generate matrix data using hicstuff . But I have some details about the usage of hicstuff you mentioned in the METHOD of  paper " Chromosome-level quality scaffolding of brown algal genomes using InstaGRAAL, a 
proximity ligation-based scaffolder "
  You say you used the parameter --maxin 5 -verysensitive-local , so could you explain the details about these parameters ? And you Hic data sequence read  is 75 bp long , so if sequencing length is 150 bp , are these parameters fittable ? Besides , you used the bowtie2 sepeartely in the paper , not use the hicstuff pipeline ? I am puzzled because I did not find  --maxin 5 -verysensitive-local in the hicstuff pipeline .
  second , in your paper , you mentioned you filterd some alignments  not fittable for some need ,such as those coverage was less than one standard deviation below the mean of the global coverage distribution ,so are these parameters also default ? or anything else ?
  Hope you can give me some advice about the usage you mentioned . Thank you .

**Comment by cmdoret** [comment]
Hello, 
I think you are right, default alignment parameters for hicstuff are defined here: https://github.com/koszullab/hicstuff/blob/830d04fffbdb14957ba95f196d7bcdd690d84da9/hicstuff/pipeline.py#L89-L101

Generally speaking, we use `local` alignment because a global alignment would not allow to partially map chimeric Hi-C reads. However if you want to use different parameters, you can map the reads with whatever software / parameters you prefer and provide the output (name-sorted) BAM files to hicstuff. 

There is a small example starting from an intermediate BAM file in the hicstuff docs: https://hicstuff.readthedocs.io/en/latest/notebooks/demo_cli.html#Starting-from-intermediate-files

I think this is what they did in the instaGRAAL paper, perhaps @baudrly  or @nadegeguiglielmoni can confirm ?

Instagraal filters fragments from the Hi-C matrix with low coverage to improve results, this is the `--coverage-std` option. One standard dev is indeed the default value.

Hope that helps

**Comment by longzhangnation** [comment]
Hello ,
  Thanks for your reply, it really helps . In other words , you just run `hicstuff pipeline` with the default parameters when you perform your experiment in the paper ?  And not setting special parameter ? Am I right ?
  Anyway , thanks for you help ,again.

**Comment by nadegeguiglielmoni** [comment]
Hello,

You can indeed run the mapping step directly with `hicstuff pipeline`. For 150 bp reads, you should definitely use the parameter  `--iterative`. You should also put the enzyme used for Hi-C library preparation as the parameter `--enzyme`. By default, the mapping tool used is bowtie2, but you can also use bwa instead if you prefer with the parameter `--aligner bwa`. 

So if you run hicstuff on a library prepared with DpnII and using bowtie2 for mapping, the command would be:
`hicstuff pipeline --enzyme DpnII --iterative --outdir hic_folder --genome assembly.fasta R1.fastq R2.fastq`

You can also look at the repository with command lines used in the paper https://github.com/koszullab/ectocarpus_scripts

**Comment by longzhangnation** [comment]
Hi @nadegeguiglielmoni ,
  Thanks for you links, I viewed the scripts and got to know the next step . 
  Have a nice day and I will close the issue.
